# Generated by Django 3.2.9 on 2022-01-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregadore',
            name='historia',
        ),
        migrations.AddField(
            model_name='entregadore',
            name='cnh',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem CNH'),
        ),
        migrations.AddField(
            model_name='entregadore',
            name='doc_moto',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Imagem documento da Moto'),
        ),
        migrations.AlterField(
            model_name='entregadore',
            name='imagem',
            field=models.ImageField(upload_to='', verbose_name='Sua foto'),
        ),
        migrations.AlterField(
            model_name='entregadore',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
    ]
