# Generated by Django 3.2.9 on 2022-01-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220106_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiro',
            name='nome',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
